# Documentation: https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: ["--no-sort-keys", "--autofix"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  # Python autoformatter
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        name: autoformat python (autopep8)

  # Python linter
  #   Fastest linter (written in Rust), includes most Python linters and autofixes,
  #   but no autoformatter and no type-checker
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.0"
    hooks:
      - id: ruff
        name: lint and fix python (ruff)
        args: [--show-fixes, --fix, --exit-non-zero-on-fix]

  # Python typechecker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        name: type-check python (mypy)
        always_run: true
        pass_filenames: false
        args: [] # disable default --ignore-missing-imports
        additional_dependencies: []

  # Python unit tests
  - repo: local
    hooks:
      - id: pytest
        name: python unit tests (pytest)
        language: system
        entry: python3 -m pytest
        always_run: true
        pass_filenames: false
